
debug: true

http:
  addr: :1323
  cors:
    origins:
     - "http://127.0.0.1:4200"
     - "http://localhost:4200"
    credentials: true
  session:
    secret: xGKCAxcCbUZyM3GayitHcQJz9HHnDNKk

log:
  format: json
  level: debug
  output: stdout

database:
  url: postgres://postgres@127.0.0.1/eternal?sslmode=disable
