## 文档采用OpenAPI标准书写，可以使用https://editor.swagger.io查看

openapi: 3.0.0
info:
  title: 十年接口文档
  description: 采用REST FULL规范
  version: 1.0.0
  contact:
    email: wiiiky@outlook.com

servers:
  - url: 'http://127.0.0.1:1323/api/'
    description: 测试环境地址
  - url: 'https://10.wikylyu.xyz/api/'
    description: 正是环境地址

# 接口分组定义
tags:
  - name: account
    description: 账号
  - name: file
    description: 文件
  - name: home
    description: 主页
  - name: question
    description: 问题

paths:
  /home/hot/answers:
    get:
      tags:
        - home
      summary: 获取热门回答
      description: 获取热门回答
      operationId: findHotAnswers
      parameters:
        - name: page
          in: query
          description: 分页
          schema:
            type: integer
          example: 1
        - name: limit
          in: query
          description: 每页显示数
          schema:
            type: integer
          example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/HotAnswer"
  /account:
    get:
      tags:
        - account
      summary: 获取账号信息
      description: 获取账号信息
      operationId: getAccount
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
    post:
      tags:
        - account
      summary: 注册账号
      description: 注册账号，必须使用手机号码注册
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthToken"
  /account/token:
    put:
      tags:
        - account
      summary: 登录
      description: 登录
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthToken"
    delete:
      tags:
        - account
      summary: 注销
      description: 注销
      operationId: logout
      responses:
        '200':
          description: OK，会同时删除浏览器的Cookie
  /file:
    post:
      tags:
        - file
      summary: 上传文件
      description: 使用FORM提交文件
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
  /answer/{id}/upvote:
    post:
      tags:
        - question
      summary: 点赞回答
      description: 点赞回答
      operationId: upvoteAnswer
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          allowEmptyValue: false
          description: 回答ID
          example: 36f20681-1276-4286-8d7a-d2847c16d6ab
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VoteAnswerResult"
  /answer/{id}/downvote:
    post:
      tags:
        - question
      summary: 踩回答
      description: 踩回答
      operationId: downvoteAnswer
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
          allowEmptyValue: false
          description: 回答ID
          example: 36f20681-1276-4286-8d7a-d2847c16d6ab
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VoteAnswerResult"
  /file/{id}:
    post:
      tags:
        - file
      summary: 下载文件
      description: 根据文件ID下载文件
      operationId: downloadFile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: 文件ID
      responses:
        '200':
          description: OK，Content-Type根据文件类型而定

components:
  schemas:
    Error:
      type: object
      description: 错误提示
      properties:
        code:
          type: integer
          description: 错误码
          example: 101
        message:
          type: string
          description: 错误信息
          example: 用户名密码错误
      required:
        - code
        - message
    Account:
      type: object
      description: 账号信息
      properties:
        id:
          type: string
          description: 账号ID
          example: 36f20681-1276-4286-8d7a-d2847c16d6ab
        country_code:
          type: string
          description: 国家码
          example: 86
        mobile:
          type: string
          description: 手机号
          example: 18621668842
        ctime:
          type: string
          format: date-time
          description: 创建时间
          example: "2018-05-17T18:13:12.677426638+08:00"
        utime:
          type: string
          format: date-time
          description: 更新时间
          example: "2018-05-17T18:13:12.677426638+08:00"
    AuthToken:
      type: object
      description: 登录凭证
      properties:
        token:
          type: string
          description: TOKEN
          example: 36f20681-1276-4286-8d7a-d2847c16d6ab
    LoginRequest:
      type: object
      description: 用户注册信息
      properties:
        mobile:
          type: string
          description: 手机号码
          example: "18621578819"
        password:
          type: string
          description: 用户密码
          example: "123456"
    SignupRequest:
      type: object
      description: 用户注册信息
      properties:
        country_code:
          type: string
          description: 国家码
          example: "86"
        mobile:
          type: string
          description: 手机号码
          example: "18621578819"
        code:
          type: string
          description: 短信验证码
          example: "123456"
        password:
          type: string
          description: 用户密码
          example: "123456"
    File:
      type: object
      description: 文件信息
      properties:
        id:
          type: string
          description: 文件ID
          example: 227982f6de2c4d2e684fcc782e0f5f89
        content_type:
          type: string
          description: 文件类型
          example: image/jpeg
    Answer:
      type: object
      description: 回答
      properties:
        id:
          type: string
          description: 回答ID
          example: 7425b2c0-626b-429f-a334-ba4176f497ad
        excerpt:
          type: string
          description: 摘要
          example: 大家好，这是摘要
        question_id:
          type: string
          description: 问题ID
          example: 7425b2c0-626b-429f-a334-ba4176f497ad
        user_id:
          type: string
          description: 回答者ID
          example: 7425b2c0-626b-429f-a334-ba4176f497ad
        view_count:
          type: integer
          description: 浏览数
          example: 123
        upvote_count:
          type: integer
          description: 点赞数
          example: 123
        downvote_count:
          type: integer
          description: 踩数
          example: 232
        ctime:
          type: string
          format: date-time
          description: 创建时间
          example: "2018-05-17T18:13:12.677426638+08:00"
        utime:
          type: string
          format: date-time
          description: 更新时间
          example: "2018-05-17T18:13:12.677426638+08:00"
    HotAnswer:
      type: object
      description: 热门回答
      properties:
        answer:
          type: object
          $ref: "#/components/schemas/Answer"
    VoteAnswerResult:
      type: object
      description: 点赞/踩回答的结果
      properties:
        upvote_count:
          type: integer
          description: 最终点赞数
          example: 123
        downvote_count:
          type: integer
          description: 最终踩数
          example: 235
