openapi: 3.0.0
info:
  title: 十年接口文档
  description: 采用REST FULL规范
  version: 1.0.0
  contact:
    email: wiiiky@outlook.com

servers:
  - url: 'http://127.0.0.1:1323/api/'
    description: 测试环境地址

# 接口分组定义
tags:
  - name: account
    description: 账号
  - name: file
    description: 文件
  - name: home
    description: 主页

paths:
  /home/hot/answers:
    get:
      tags:
        - home
      summary: 获取热门回答
      description: 获取热门回答
      operationId: findHotAnswers
      parameters:
        - name: page
          in: query
          description: 分页
          schema:
            type: integer
          example: 1
        - name: limit
          in: query
          description: 每页显示数
          schema:
            type: integer
          example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  $ref: "#/components/schemas/HotAnswer"
  /account:
    post:
      tags:
         - account
      summary: 注册账号
      description: 注册账号，必须使用手机号码注册
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthToken"
  /file:
    post:
      tags:
         - file
      summary: 上传文件
      description: 使用FORM提交文件
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
  /file/{id}:
    post:
      tags:
         - file
      summary: 下载文件
      description: 根据文件ID下载文件
      operationId: downloadFile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: 文件ID
      responses:
        '200':
          description: OK，Content-Type根据文件类型而定

components:
  schemas:
    Error:
      type: object
      description: 错误提示
      properties:
        code:
          type: integer
          description: 错误码
          example: 101
        message:
          type: string
          description: 错误信息
          example: 用户名密码错误
      required:
        - code
        - message
    AuthToken:
      type: object
      description: 登录凭证
      properties:
        token:
          type: string
          description: TOKEN
          example: 36f20681-1276-4286-8d7a-d2847c16d6ab
    RegisterRequest:
      type: object
      description: 用户注册信息
      properties:
        country_code:
          type: string
          description: 国家码
          example: "86"
        mobile:
          type: string
          description: 手机号码
          example: "18621578819"
        code:
          type: string
          description: 短信验证码
          example: "123456"
        password:
          type: string
          description: 用户密码
          example: "123456"
    File:
      type: object
      description: 文件信息
      properties:
        id:
          type: string
          description: 文件ID
          example: 227982f6de2c4d2e684fcc782e0f5f89
        content_type:
          type: string
          description: 文件类型
          example: image/jpeg
    HotAnswer:
      type: object
      description: 热门回答
      properties:
        id:
          type: string
          description: ID
